"""Module registry for SafeX Solutions Week 5 - AI Products & Prototypes Suite."""

from typing import Any, Dict

MODULE_REGISTRY: Dict[str, Dict[str, Dict[str, Any]]] = {
    "week5": {
        "chatbot_arsalan": {
            "name": "Client-Ready Customer Support Chatbot",
            "developer": "Arsalan Qasim",
            "role": "Group Leader",
            "institution": "COMSATS University Islamabad",
            "task": "AI Customer Support Chatbot (Client-Ready)",
            "domain": "E-Commerce & Retail",
            "status": "Submitted",
            "deployed_url": "https://safex-group54-portfolio.streamlit.app",
            "description": "Production-grade AI chatbot automating e-commerce customer support FAQs, sentiment-aware human handoff, real-time logging, benchmark tester, and persistent no-code admin panel.",
        },
        "lead_gen_wasim": {
            "name": "AI Lead Generation & Scoring Pipeline",
            "developer": "MUHAMMAD WASIM",
            "role": "Team Member",
            "institution": "UET Peshawar",
            "task": "AI-Powered Lead Generation & Qualification Tool",
            "domain": "Real Estate Agencies",
            "status": "In progress",
            "deployed_url": "",
            "description": "Automated lead intake, rubric-based qualification scoring, hot-lead flagging, and AI summary generation.",
        },
        "bi_dashboard_faozan": {
            "name": "AI Business Intelligence & Forecasting Suite",
            "developer": "Muhammad Faozan Mujtaba",
            "role": "Team Member",
            "institution": "NUST H-12",
            "task": "AI Business Intelligence Dashboard",
            "domain": "E-Commerce & Digital Products",
            "status": "Submission Ready",
            "deployed_url": "",
            "description": "Executive analytics over 180 days of e-commerce data: like-for-like KPIs, a revenue forecast backtested at 6.7% MAPE on unseen data, episode-grouped anomaly detection, and a weekly narrative composed only from figures the engine computed.",
        },
        "chatbot_shahidullah": {
            "name": "Healthcare & Clinic AI Chatbot",
            "developer": "Shahidullah",
            "role": "Team Member",
            "institution": "Bahria University",
            "task": "AI Customer Support Chatbot (Client-Ready)",
            "domain": "Healthcare & Medical Clinics",
            "status": "In progress",
            "deployed_url": "",
            "description": "Automated patient query assistant, appointment inquiry handler, and clinic hours FAQ responder.",
        },
        "lead_gen_ali_ammar": {
            "name": "B2B Sales Lead Qualification Agent",
            "developer": "Ali Ammar Haider",
            "role": "Team Member",
            "institution": "COMSATS University Islamabad",
            "task": "AI-Powered Lead Generation & Qualification Tool",
            "domain": "B2B Professional Services",
            "status": "In progress",
            "deployed_url": "",
            "description": "Intelligent inbound lead scoring evaluating budget, timeline urgency, and company fit.",
        },
        "bi_dashboard_abdul_haseeb": {
            "name": "Marketing Agency BI Analytics Hub",
            "developer": "Abdul Haseeb",
            "role": "Team Member",
            "institution": "COMSATS University Islamabad",
            "task": "AI Business Intelligence Dashboard",
            "domain": "Marketing & Ad Agencies",
            "status": "In progress",
            "deployed_url": "",
            "description": "Campaign performance tracking, CAC/LTV forecasting, and plain-English AI executive insights.",
        },
        "chatbot_hammad": {
            "name": "Logistics & Courier AI Support Bot",
            "developer": "Hammad Abbas",
            "role": "Team Member",
            "institution": "Agriculture University of Peshawar",
            "task": "AI Customer Support Chatbot (Client-Ready)",
            "domain": "Logistics & Courier Services",
            "status": "In progress",
            "deployed_url": "",
            "description": "Tracking lookup assistant, delivery exception handler, and rates FAQ bot.",
        },
        "lead_gen_ali_zaib": {
            "name": "Insurance & Finance Lead Qualifier",
            "developer": "Ali Zaib",
            "role": "Team Member",
            "institution": "COMSATS University Islamabad",
            "task": "AI-Powered Lead Generation & Qualification Tool",
            "domain": "Insurance & Wealth Management",
            "status": "Submission Ready",
            "deployed_url": "https://insurance-lead-qualifier-wgihzpbzbfeaeozplkp8ym.streamlit.app/",
            "description": "Transparent, five-factor weighted lead scoring model (policy value, budget fit, urgency, risk profile, engagement channel) with single-lead and batch scoring, qualitative risk flags, and full test coverage.",
        },
        "bi_dashboard_malik_sudais": {
            "name": "Retail Multi-Store BI Dashboard",
            "developer": "Malik Sudais",
            "role": "Team Member",
            "institution": "Sarhad University",
            "task": "AI Business Intelligence Dashboard",
            "domain": "Retail Chains",
            "status": "In progress",
            "deployed_url": "",
            "description": "Inventory movement analytics, store sales trends, and automated AI replenishment alerts.",
        },
    }
}
