"""Build a standalone deployment package for the Chinar Cart BI dashboard.

Week 5 module owned by Muhammad Faozan Mujtaba.

The shared ``week5/deploy_prep.py`` packages the group leader's chatbot module and
hardcodes its paths. This module-local script does the same job for this module, following
the precedent set in Week 4 by ``week4/knowledge_assistant_deploy_package/``.

Run it from the week5 folder:

    python src/modules/bi_dashboard_faozan/deploy_prep.py

The package keeps the module's real import paths, so the deployed code is byte-identical
to the reviewed code and no import rewriting can silently change behaviour between them.
"""

from __future__ import annotations

import shutil
from pathlib import Path

MODULE_DIR = Path(__file__).resolve().parent
WEEK5_DIR = MODULE_DIR.parents[2]
PACKAGE_DIR = WEEK5_DIR / "bi_dashboard_deploy_package"
MODULE_NAME = "bi_dashboard_faozan"

SOURCE_FILES = ["__init__.py", "engine.py", "narrative.py", "ui.py", "generate_dataset.py"]

APP_ENTRYPOINT = '''"""Standalone entrypoint for the Chinar Cart BI & Forecasting Suite.

Generated by src/modules/bi_dashboard_faozan/deploy_prep.py - do not edit here.
Edit the module in week5/src/modules/bi_dashboard_faozan/ and regenerate.
"""

import sys
from pathlib import Path

import streamlit as st

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

st.set_page_config(
    page_title="Chinar Cart BI Dashboard",
    page_icon="\\U0001F4C8",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Standalone deployment has no shared shell, so the module supplies its own styling.
st.markdown(
    """
    <style>
    [data-testid="stSidebarNav"] { display: none !important; }
    footer { visibility: hidden; }
    .block-container { max-width: 1180px; padding-top: 3rem; padding-bottom: 4rem; }
    .hero-wrap { background: rgba(127, 127, 127, 0.06); border: 1px solid rgba(127, 127, 127, 0.25);
        border-radius: 12px; padding: 1.5rem 1.75rem; margin-bottom: 1.5rem; }
    .hero-badge { display: inline-block; font-size: 0.75rem; font-weight: 700; text-transform: uppercase;
        letter-spacing: 0.05em; color: #0f766e; background: #e6f5f2; padding: 0.25rem 0.6rem;
        border-radius: 999px; margin-bottom: 0.5rem; }
    .hero-title { font-size: 1.6rem; font-weight: 800; margin-bottom: 0.25rem; }
    .hero-subtitle { font-size: 0.95rem; opacity: 0.85; line-height: 1.5; }
    .side-heading { font-size: 0.72rem; font-weight: 700; letter-spacing: 0.08em;
        text-transform: uppercase; opacity: 0.7; margin: 1.35rem 0 0.4rem; }
    </style>
    """,
    unsafe_allow_html=True,
)

with st.sidebar:
    st.radio("Color mode", ["Light", "Dark"], key="ui_theme_choice", horizontal=True)

from src.modules.bi_dashboard_faozan.ui import render_ui

if __name__ == "__main__":
    render_ui()
'''

REQUIREMENTS = """streamlit>=1.36.0
pandas>=2.0.0
numpy>=1.24.0
scikit-learn>=1.3.0
matplotlib>=3.7.0
"""

PACKAGE_INIT = '"""Standalone deployment package for the Chinar Cart BI dashboard."""\n'


def prepare_standalone_package() -> Path:
    """Create the deployment folder and return its path."""
    print("=" * 70)
    print("  SafeX Group 54 - Chinar Cart BI Dashboard Packager")
    print("=" * 70)

    if PACKAGE_DIR.exists():
        shutil.rmtree(PACKAGE_DIR)

    module_target = PACKAGE_DIR / "src" / "modules" / MODULE_NAME
    module_target.mkdir(parents=True, exist_ok=True)
    print(f"[+] Created package directory: {PACKAGE_DIR}")

    missing = [name for name in SOURCE_FILES if not (MODULE_DIR / name).exists()]
    if missing:
        raise FileNotFoundError(f"Module source files missing: {', '.join(missing)}")

    for name in SOURCE_FILES:
        shutil.copy2(MODULE_DIR / name, module_target / name)
    print(f"[+] Copied {len(SOURCE_FILES)} module source files (imports unchanged).")

    shutil.copytree(MODULE_DIR / "data", module_target / "data")
    print("[+] Copied the committed dataset, so the deployed figures match the reviewed ones.")

    (PACKAGE_DIR / "src" / "__init__.py").write_text(PACKAGE_INIT, encoding="utf-8")
    (PACKAGE_DIR / "src" / "modules" / "__init__.py").write_text(PACKAGE_INIT, encoding="utf-8")

    (PACKAGE_DIR / "app.py").write_text(APP_ENTRYPOINT, encoding="utf-8")
    (PACKAGE_DIR / "requirements.txt").write_text(REQUIREMENTS, encoding="utf-8")
    print("[+] Wrote standalone app.py and requirements.txt.")

    print("\n" + "=" * 70)
    print("  PACKAGE READY")
    print("=" * 70)
    print(f"Location: {PACKAGE_DIR}\n")
    print("Verify locally:")
    print(f"   cd {PACKAGE_DIR}")
    print("   streamlit run app.py\n")
    print("Deploy on Streamlit Community Cloud:")
    print("   Push this folder to its own GitHub repo, then at share.streamlit.io")
    print("   pick the repo and set the main file to app.py.")
    print("   No secrets are required: the dashboard runs fully offline.")
    print("   Remember to set app Sharing to 'public' or reviewers hit a login wall.\n")
    print("Then set 'deployed_url' for bi_dashboard_faozan in week5/src/modules/registry.py.")
    print("=" * 70)
    return PACKAGE_DIR


if __name__ == "__main__":
    prepare_standalone_package()
