# AI Email Assistant Prototype - Engine
# Assigned Developer: Shahidullah (Group Member)
# For SafeX Solutions Business Automation Research
#
# This module contains the core (non-UI) logic for the AI Email Assistant:
# rule-based customer-email analysis (category / priority / sentiment /
# keywords), a lightweight confidence score, and reply generation that uses
# the Gemini API when a key is supplied and falls back to polished,
# template-based replies otherwise.

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Dict, List, Optional

try:
    import google.generativeai as genai
except ImportError:  # pragma: no cover - library is optional at runtime
    genai = None


# ==============================================================================
# Static knowledge base used by the rule-based analyzer
# ==============================================================================

# Ordered so that more specific / higher-signal categories are checked before
# generic ones. Order matters because the first category with a keyword hit
# wins.
CATEGORY_KEYWORDS: Dict[str, List[str]] = {
    "Refund": ["refund", "money back", "reimburse", "chargeback"],
    "Replacement": ["replace", "replacement", "exchange", "swap the item"],
    "Complaint": [
        "complaint", "disappointed", "unacceptable", "terrible",
        "damaged", "broken", "defective", "poor quality", "worst",
    ],
    "Order Status": [
        "order status", "track", "tracking", "where is my order",
        "when will i receive", "delivery date", "order number",
    ],
    "Shipping": ["shipping", "courier", "dispatch", "delayed shipment", "ship "],
    "Payment": [
        "payment", "invoice", "billed", "billing", "transaction",
        "charged twice", "double charge", "paid",
    ],
    "Product Inquiry": [
        "product", "specification", "feature", "compatible",
        "how does it work", "price of", "does it come with",
    ],
}

HIGH_PRIORITY_WORDS: List[str] = [
    "urgent", "asap", "immediately", "right now", "emergency",
    "legal action", "lawyer", "escalate", "furious", "unacceptable",
    "third time", "cancel my order",
]

MEDIUM_PRIORITY_WORDS: List[str] = [
    "soon", "please help", "waiting", "still no reply", "again",
    "concerned", "disappointed",
]

NEGATIVE_SENTIMENT_WORDS: List[str] = [
    "bad", "late", "broken", "damage", "damaged", "complaint", "angry",
    "refund", "disappointed", "unacceptable", "terrible", "worst",
    "frustrated", "never again", "poor",
]

POSITIVE_SENTIMENT_WORDS: List[str] = [
    "thanks", "thank you", "great", "good", "appreciate", "excellent",
    "happy", "love", "awesome", "wonderful",
]

# Common English stop words excluded from the extracted keyword list.
STOP_WORDS: set = {
    "the", "a", "an", "and", "or", "but", "is", "are", "was", "were", "to",
    "of", "in", "on", "for", "with", "this", "that", "it", "i", "my", "me",
    "you", "your", "we", "our", "us", "have", "has", "had", "be", "been",
    "as", "at", "by", "from", "will", "would", "can", "could", "please",
    "hi", "hello", "dear", "regards", "thanks", "thank",
}


@dataclass
class EmailAnalysis:
    """Structured result of analyzing a single customer email."""

    category: str
    priority: str
    sentiment: str
    keywords: List[str] = field(default_factory=list)
    confidence: float = 0.0
    summary: str = ""
    suggested_subject: str = ""

    def as_dict(self) -> Dict[str, object]:
        """Return the analysis as a plain dictionary."""
        return {
            "category": self.category,
            "priority": self.priority,
            "sentiment": self.sentiment,
            "keywords": self.keywords,
            "confidence": self.confidence,
            "summary": self.summary,
            "suggested_subject": self.suggested_subject,
        }


class EmailAssistantEngine:
    """Core engine powering the AI Email Assistant prototype.

    The engine performs rule-based analysis of an incoming customer email
    (category, priority, sentiment, keywords) and produces a professional
    reply. When a valid Gemini API key is supplied, replies are generated by
    the ``gemini-2.5-flash`` model; otherwise a curated set of business
    templates is used, keeping the module fully functional offline.
    """

    #: Reply templates keyed by category, used whenever no API key is set
    #: or whenever the Gemini API call fails for any reason.
    REPLY_TEMPLATES: Dict[str, str] = {
        "Refund": (
            "Dear Customer,\n\n"
            "Thank you for reaching out to SafeX Solutions. We're sorry to "
            "hear about your experience and understand your request for a "
            "refund.\n\n"
            "Your request has been logged and our billing team will process "
            "it within 3-5 business days. You will receive a confirmation "
            "email once the refund has been issued.\n\n"
            "Kind Regards,\nSafeX Support Team"
        ),
        "Replacement": (
            "Dear Customer,\n\n"
            "Thank you for letting us know about the issue with your item. "
            "We apologize for the inconvenience this has caused.\n\n"
            "We have started processing a replacement for you, and a member "
            "of our team will confirm shipping details shortly.\n\n"
            "Kind Regards,\nSafeX Support Team"
        ),
        "Complaint": (
            "Dear Customer,\n\n"
            "We sincerely apologize for the experience you've described. "
            "This falls short of the standard we aim to provide.\n\n"
            "Our support team is reviewing your case and will follow up "
            "directly to make this right as quickly as possible.\n\n"
            "Kind Regards,\nSafeX Support Team"
        ),
        "Order Status": (
            "Dear Customer,\n\n"
            "Thank you for reaching out about your order. We are currently "
            "checking the latest status with our fulfillment team and will "
            "send you an update shortly with the most current tracking "
            "information.\n\n"
            "Kind Regards,\nSafeX Support Team"
        ),
        "Shipping": (
            "Dear Customer,\n\n"
            "Thank you for your patience regarding your shipment. We are "
            "coordinating with our courier partner to confirm the latest "
            "delivery timeline and will update you as soon as we hear "
            "back.\n\n"
            "Kind Regards,\nSafeX Support Team"
        ),
        "Payment": (
            "Dear Customer,\n\n"
            "Thank you for bringing this payment matter to our attention. "
            "Our billing team is reviewing your transaction and will "
            "contact you shortly with a full breakdown and resolution.\n\n"
            "Kind Regards,\nSafeX Support Team"
        ),
        "Product Inquiry": (
            "Dear Customer,\n\n"
            "Thank you for your interest in our products. We've noted your "
            "question and one of our product specialists will follow up "
            "shortly with detailed information to help you decide.\n\n"
            "Kind Regards,\nSafeX Support Team"
        ),
        "General Inquiry": (
            "Dear Customer,\n\n"
            "Thank you for contacting SafeX Solutions. We appreciate you "
            "reaching out and will respond to your message as soon as "
            "possible.\n\n"
            "Best Regards,\nSafeX Support Team"
        ),
    }

    def __init__(self, api_key: Optional[str] = None) -> None:
        """Initialize the engine, optionally enabling Gemini-based replies.

        Args:
            api_key: Optional Gemini API key. When provided (and the
                ``google-generativeai`` package is installed), replies are
                generated by the Gemini model. Otherwise, the engine falls
                back to template-based replies automatically.
        """
        self.api_enabled: bool = False
        self.api_error: Optional[str] = None
        self._model = None

        if api_key:
            if genai is None:
                self.api_error = (
                    "google-generativeai is not installed; using template "
                    "replies instead."
                )
            else:
                try:
                    genai.configure(api_key=api_key)
                    self._model = genai.GenerativeModel("gemini-2.5-flash")
                    self.api_enabled = True
                except Exception as exc:  # noqa: BLE001 - surface to caller
                    self.api_error = f"Could not initialize Gemini client: {exc}"

    # --------------------------------------------------------------------
    # Analysis helpers
    # --------------------------------------------------------------------

    @staticmethod
    def _normalize(text: str) -> str:
        """Lowercase and collapse whitespace for reliable keyword matching."""
        return re.sub(r"\s+", " ", text or "").strip().lower()

    def detect_category(self, email: str) -> str:
        """Detect the most likely customer-service category for an email."""
        normalized = self._normalize(email)

        for category, phrases in CATEGORY_KEYWORDS.items():
            if any(phrase in normalized for phrase in phrases):
                return category

        return "General Inquiry"

    def detect_priority(self, email: str) -> str:
        """Estimate the urgency of the email: High, Medium, or Low."""
        normalized = self._normalize(email)

        if any(word in normalized for word in HIGH_PRIORITY_WORDS):
            return "High"

        if any(word in normalized for word in MEDIUM_PRIORITY_WORDS):
            return "Medium"

        # An exclamation-heavy message is a soft signal of urgency too.
        if normalized.count("!") >= 2:
            return "Medium"

        return "Low"

    def detect_sentiment(self, email: str) -> str:
        """Estimate the overall sentiment: Positive, Neutral, or Negative."""
        normalized = self._normalize(email)

        negative_hits = sum(1 for w in NEGATIVE_SENTIMENT_WORDS if w in normalized)
        positive_hits = sum(1 for w in POSITIVE_SENTIMENT_WORDS if w in normalized)

        if negative_hits > positive_hits:
            return "Negative"
        if positive_hits > negative_hits:
            return "Positive"
        return "Neutral"

    def extract_keywords(self, email: str, limit: int = 8) -> List[str]:
        """Extract simple, frequency-based keywords from the email body.

        This is a lightweight, dependency-free keyword extractor: it tokenizes
        the text, drops stop words and short tokens, and returns the most
        frequent remaining words in order of appearance.
        """
        normalized = self._normalize(email)
        tokens = re.findall(r"[a-zA-Z']{3,}", normalized)

        seen: Dict[str, int] = {}
        order: List[str] = []
        for token in tokens:
            if token in STOP_WORDS:
                continue
            if token not in seen:
                order.append(token)
            seen[token] = seen.get(token, 0) + 1

        # Sort candidates by frequency (desc) while keeping first-seen order
        # as a tiebreaker, then cap to `limit`.
        ranked = sorted(order, key=lambda t: (-seen[t], order.index(t)))
        return ranked[:limit]

    def generate_summary(self, email: str, max_length: int = 160) -> str:
        """Produce a short, one-line summary of the customer's issue."""
        normalized = " ".join((email or "").split())
        if not normalized:
            return "No content provided."

        # Prefer the first sentence; fall back to a truncated snippet.
        first_sentence = re.split(r"(?<=[.!?])\s", normalized)[0]
        summary = first_sentence if len(first_sentence) <= max_length else normalized

        if len(summary) > max_length:
            summary = summary[: max_length - 1].rstrip() + "…"

        return summary

    def suggest_subject(self, email: str, category: str) -> str:
        """Suggest a concise, professional subject line for the reply."""
        subject_map = {
            "Refund": "Your Refund Request - SafeX Solutions",
            "Replacement": "Replacement Update for Your Order",
            "Complaint": "We're Looking Into Your Concern",
            "Order Status": "Update on Your Order Status",
            "Shipping": "Shipping Update for Your Order",
            "Payment": "Regarding Your Recent Payment",
            "Product Inquiry": "Answering Your Product Question",
            "General Inquiry": "Thank You for Contacting SafeX Solutions",
        }
        return subject_map.get(category, "Re: Your Message to SafeX Solutions")

    def compute_confidence(self, email: str, category: str, priority: str) -> float:
        """Compute a simple heuristic confidence score (0-100) for the analysis.

        The score rewards longer, keyword-rich messages and messages that
        matched a specific (non-generic) category, since those signals give
        the rule-based classifier more to work with.
        """
        normalized = self._normalize(email)
        word_count = len(normalized.split())

        score = 40.0
        if category != "General Inquiry":
            score += 30.0
        if priority != "Low":
            score += 10.0
        score += min(word_count / 2, 20.0)

        return round(min(score, 99.0), 1)

    def analyze(self, email: str) -> EmailAnalysis:
        """Run the full rule-based analysis pipeline on a customer email."""
        category = self.detect_category(email)
        priority = self.detect_priority(email)
        sentiment = self.detect_sentiment(email)
        keywords = self.extract_keywords(email)
        confidence = self.compute_confidence(email, category, priority)
        summary = self.generate_summary(email)
        subject = self.suggest_subject(email, category)

        return EmailAnalysis(
            category=category,
            priority=priority,
            sentiment=sentiment,
            keywords=keywords,
            confidence=confidence,
            summary=summary,
            suggested_subject=subject,
        )

    # --------------------------------------------------------------------
    # Reply generation
    # --------------------------------------------------------------------

    def _generate_ai_reply(
        self,
        email: str,
        analysis: EmailAnalysis,
        style: str = "Professional",
        language: str = "English",
    ) -> Optional[str]:
        """Attempt to generate a reply via the Gemini API.

        Returns ``None`` (instead of raising) on failure so the caller can
        gracefully fall back to a template reply.
        """
        if not self.api_enabled or self._model is None:
            return None

        prompt = f"""You are a customer support representative for SafeX
Solutions, writing in a {style.lower()} tone.

Write a concise business email reply to the customer below, in {language}.
Keep it under 150 words, avoid over-promising, and sign off as
"SafeX Support Team".

Detected category: {analysis.category}
Detected priority: {analysis.priority}
Detected sentiment: {analysis.sentiment}

Customer Email:
\"\"\"
{email}
\"\"\"

Reply with the email body only (no subject line)."""

        try:
            response = self._model.generate_content(prompt)
            text = getattr(response, "text", None)
            return text.strip() if text else None
        except Exception as exc:  # noqa: BLE001 - degrade gracefully
            self.api_error = f"Gemini API call failed, used template reply instead: {exc}"
            return None

    def generate_reply(
        self,
        email: str,
        analysis: Optional[EmailAnalysis] = None,
        style: str = "Professional",
        language: str = "English",
    ) -> str:
        """Generate a professional reply for the given customer email.

        Uses the Gemini API when available and successful; otherwise falls
        back to a curated, category-specific template. ``style`` and
        ``language`` are honored by the AI path; the offline template path
        is always English/professional (documented limitation, surfaced in
        the UI layer).
        """
        analysis = analysis or self.analyze(email)

        ai_reply = self._generate_ai_reply(email, analysis, style=style, language=language)
        if ai_reply:
            return ai_reply

        return self.REPLY_TEMPLATES.get(
            analysis.category, self.REPLY_TEMPLATES["General Inquiry"]
        )

    # --------------------------------------------------------------------
    # Public entry point
    # --------------------------------------------------------------------

    def process_email(
        self,
        email: str,
        style: str = "Professional",
        language: str = "English",
    ) -> Dict[str, object]:
        """Analyze a customer email and generate a reply in one call.

        Args:
            email: The raw customer email text.
            style: Desired reply tone (e.g. "Professional", "Friendly",
                "Formal", "Empathetic"). Honored by the AI (Gemini) path.
            language: Desired reply language. Honored by the AI (Gemini)
                path; the offline template path remains English.

        Returns a dictionary containing the full analysis, the generated
        reply, whether the AI (Gemini) path was used, and basic reply
        metrics (character / word counts) that are convenient for display
        in the UI layer.
        """
        if not email or not email.strip():
            raise ValueError("Email content cannot be empty.")

        analysis = self.analyze(email)
        reply = self.generate_reply(email, analysis, style=style, language=language)

        result: Dict[str, object] = analysis.as_dict()
        result.update(
            {
                "reply": reply,
                "used_ai": self.api_enabled and self.api_error is None,
                "api_note": self.api_error,
                "reply_char_count": len(reply),
                "reply_word_count": len(reply.split()),
            }
        )
        return result