"""Module registry for SafeX Solutions Week 6 - Sell Your Skills Suite."""

from typing import Any, Dict

MODULE_REGISTRY: Dict[str, Dict[str, Dict[str, Any]]] = {
    "week6": {
        "commercial_arsalan": {
            "name": "Commercialization Command Center & Outreach Suite",
            "developer": "Arsalan Qasim",
            "role": "Group Leader",
            "institution": "COMSATS University Islamabad",
            "task": "Monetize AI Customer Support Chatbot",
            "service_offering": "Turnkey 24/7 AI Customer Support Automation for E-Commerce & Retail Brands",
            "target_markets": "USA, UK, UAE, Saudi Arabia, Qatar, Canada, Australia",
            "status": "Submitted",
            "deployed_url": "https://safex-group54-portfolio.streamlit.app",
            "description": "Full commercialization engine: 3-tier pricing calculator, automated cold email generator, 15+ real international prospects with live Excel pipeline tracker, social media marketing hub, and group consolidation dashboard.",
        },
        "commercial_wasim": {
            "name": "Lead Qualification Agency Commercial Deck",
            "developer": "MUHAMMAD WASIM",
            "role": "Team Member",
            "institution": "UET Peshawar",
            "task": "Monetize AI Lead Gen Tool",
            "service_offering": "Automated Inbound Lead Qualification & CRM Scoring for Real Estate",
            "target_markets": "UAE, UK, USA",
            "status": "In progress",
            "deployed_url": "",
            "description": "Commercial agency proposal, real estate pricing calculator, and cold outreach sequences.",
        },
        "commercial_faozan": {
            "name": "BI Dashboard Monthly Reporting Service",
            "developer": "Muhammad Faozan Mujtaba",
            "role": "Team Member",
            "institution": "NUST H-12",
            "task": "Monetize AI BI Dashboard",
            "service_offering": "Executive BI Analytics & AI Narrative Reporting for E-Commerce",
            "target_markets": "USA, Canada, Europe",
            "status": "In progress",
            "deployed_url": "",
            "description": "Productized BI reporting subscription, analytics pricing packages, and client pitch deck.",
        },
        "commercial_shahidullah": {
            "name": "Clinic AI Chatbot Monetization Hub",
            "developer": "Shahidullah",
            "role": "Team Member",
            "institution": "Bahria University",
            "task": "Monetize AI Customer Support Chatbot",
            "service_offering": "24/7 Patient FAQ & Appointment Booking Assistant for Healthcare Clinics",
            "target_markets": "UAE, UK, Pakistan",
            "status": "In progress",
            "deployed_url": "",
            "description": "Clinic service packages, patient triage proposal, and clinic outreach log.",
        },
        "commercial_ali_ammar": {
            "name": "B2B Sales Qualification Commercial Agency",
            "developer": "Ali Ammar Haider",
            "role": "Team Member",
            "institution": "COMSATS University Islamabad",
            "task": "Monetize AI Lead Gen Tool",
            "service_offering": "B2B Outbound Lead Enrichment & Qualification Pipeline",
            "target_markets": "USA, UK, Australia",
            "status": "In progress",
            "deployed_url": "",
            "description": "B2B lead generation package, agency retainer model, and cold outreach templates.",
        },
        "commercial_abdul_haseeb": {
            "name": "Marketing Agency BI Analytics Pitch",
            "developer": "Abdul Haseeb",
            "role": "Team Member",
            "institution": "COMSATS University Islamabad",
            "task": "Monetize AI BI Dashboard",
            "service_offering": "Automated Client Marketing Performance Dashboards & Insights",
            "target_markets": "USA, UK, UAE",
            "status": "In progress",
            "deployed_url": "",
            "description": "White-label agency dashboard setup, client reporting retainer, and cold email sequence.",
        },
        "commercial_hammad": {
            "name": "Logistics Bot Commercial Package",
            "developer": "Hammad Abbas",
            "role": "Team Member",
            "institution": "Agriculture University of Peshawar",
            "task": "Monetize AI Customer Support Chatbot",
            "service_offering": "Real-Time Tracking & Delivery Exception Automation for Courier Brands",
            "target_markets": "Pakistan, UAE, Saudi Arabia",
            "status": "In progress",
            "deployed_url": "",
            "description": "Logistics chatbot pricing tiers, courier outreach tracker, and client proposal deck.",
        },
        "commercial_ali_zaib": {
            "name": "Insurance Lead Scoring Commercial Service",
            "developer": "Ali Zaib",
            "role": "Team Member",
            "institution": "COMSATS University Islamabad",
            "task": "Monetize AI Lead Gen Tool",
            "service_offering": "Policyholder Intent Qualification Model for Insurance Agencies",
            "target_markets": "USA, UK, Canada",
            "status": "Submission Ready",
            "deployed_url": "",
            "description": "Insurance underwriting qualifier package with tiered pricing (Broker Starter/Agency Pro/Underwriting Enterprise), an interactive ROI calculator, a personalized cold outreach generator, and an outreach pipeline tracker.",
        },
        "commercial_malik_sudais": {
            "name": "Retail Multi-Store BI Commercial Suite",
            "developer": "Malik Sudais",
            "role": "Team Member",
            "institution": "Sarhad University",
            "task": "Monetize AI BI Dashboard",
            "service_offering": "Retail Multi-Branch Inventory & Sales Velocity Analytics",
            "target_markets": "UAE, Saudi Arabia, Pakistan",
            "status": "In progress",
            "deployed_url": "",
            "description": "Retail analytics proposal, multi-location pricing tiers, and retail outreach log.",
        },
    }
}
