"""Standalone entrypoint for the Chinar Cart BI & Forecasting Suite.

Generated by src/modules/bi_dashboard_faozan/deploy_prep.py - do not edit here.
Edit the module in week5/src/modules/bi_dashboard_faozan/ and regenerate.
"""

import sys
from pathlib import Path

import streamlit as st

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

st.set_page_config(
    page_title="Chinar Cart BI Dashboard",
    page_icon="\U0001F4C8",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Standalone deployment has no shared shell, so the module supplies its own styling.
st.markdown(
    """
    <style>
    [data-testid="stSidebarNav"] { display: none !important; }
    footer { visibility: hidden; }
    .block-container { max-width: 1180px; padding-top: 3rem; padding-bottom: 4rem; }
    .hero-wrap { background: rgba(127, 127, 127, 0.06); border: 1px solid rgba(127, 127, 127, 0.25);
        border-radius: 12px; padding: 1.5rem 1.75rem; margin-bottom: 1.5rem; }
    .hero-badge { display: inline-block; font-size: 0.75rem; font-weight: 700; text-transform: uppercase;
        letter-spacing: 0.05em; color: #0f766e; background: #e6f5f2; padding: 0.25rem 0.6rem;
        border-radius: 999px; margin-bottom: 0.5rem; }
    .hero-title { font-size: 1.6rem; font-weight: 800; margin-bottom: 0.25rem; }
    .hero-subtitle { font-size: 0.95rem; opacity: 0.85; line-height: 1.5; }
    .side-heading { font-size: 0.72rem; font-weight: 700; letter-spacing: 0.08em;
        text-transform: uppercase; opacity: 0.7; margin: 1.35rem 0 0.4rem; }
    </style>
    """,
    unsafe_allow_html=True,
)

with st.sidebar:
    st.radio("Color mode", ["Light", "Dark"], key="ui_theme_choice", horizontal=True)

from src.modules.bi_dashboard_faozan.ui import render_ui

if __name__ == "__main__":
    render_ui()
