"""Standalone entrypoint for the Indus Air RAG Knowledge Assistant.

Generated by src/modules/knowledge_assistant_airline/deploy_prep.py - do not edit here.
Edit the module in week4/src/modules/knowledge_assistant_airline/ and regenerate.
"""

import sys
from pathlib import Path

import streamlit as st

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

st.set_page_config(
    page_title="Indus Air Knowledge Assistant",
    page_icon="📚",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# Standalone deployment has no shared shell, so the module supplies its own styling.
st.markdown(
    """
    <style>
    [data-testid="stSidebarNav"] { display: none !important; }
    footer { visibility: hidden; }
    .block-container { max-width: 1180px; padding-top: 3rem; padding-bottom: 4rem; }
    .hero-wrap { background: rgba(127, 127, 127, 0.06); border: 1px solid rgba(127, 127, 127, 0.25);
        border-radius: 12px; padding: 1.5rem 1.75rem; margin-bottom: 1.5rem; }
    .hero-badge { display: inline-block; font-size: 0.75rem; font-weight: 700; text-transform: uppercase;
        letter-spacing: 0.05em; color: #0f766e; background: #e6f5f2; padding: 0.25rem 0.6rem;
        border-radius: 999px; margin-bottom: 0.5rem; }
    .hero-title { font-size: 1.6rem; font-weight: 800; margin-bottom: 0.25rem; }
    .hero-subtitle { font-size: 0.95rem; opacity: 0.8; line-height: 1.5; }
    </style>
    """,
    unsafe_allow_html=True,
)

from src.modules.knowledge_assistant_airline.ui import render_ui

if __name__ == "__main__":
    render_ui()
