"""Streamlit UI for the Indus Air RAG Knowledge Assistant.

Week 4 Client-Ready Sprint module owned by Muhammad Faozan Mujtaba.

All page-level configuration stays in ``week4/src/app.py``. This file exposes a single
self-contained ``render_ui()`` as required by the harness, and holds no business logic:
everything it displays comes from ``engine.py``.
"""

from __future__ import annotations

from typing import Any

import pandas as pd
import streamlit as st

from src.modules.knowledge_assistant_airline.engine import (
    DEFAULT_SIMILARITY_FLOOR,
    DEFAULT_TOP_K,
    TARGET_COMPANY,
    AirlineKnowledgeAssistant,
    export_answer_json,
)
from src.modules.registry import MODULE_REGISTRY

SAMPLE_QUESTIONS = [
    "How much hand luggage can I take on board?",
    "What is the checked baggage allowance on an Indus Flex ticket to Dubai?",
    "My flight was delayed four hours because of an engineering fault. What am I owed?",
    "Can my 7 year old fly alone and what does it cost?",
    "Is a power bank allowed in my checked suitcase?",
    "When do my IndusMiles points expire?",
    "What is the wifi password on board?",
]


@st.cache_resource(show_spinner=False)
def _load_assistant() -> AirlineKnowledgeAssistant:
    """Build the index once per server process rather than on every rerun."""
    return AirlineKnowledgeAssistant()


def _render_header(metadata: dict[str, Any]) -> None:
    st.markdown(
        f"""
        <div class="hero-wrap">
            <div class="hero-badge">📚 RAG Knowledge Assistant · Week 4 Client Sprint</div>
            <div class="hero-title">{metadata["title"]} · {TARGET_COMPANY}</div>
            <div class="hero-subtitle">
                Grounded question answering over {TARGET_COMPANY}'s policy library, built for
                contact-centre agents who currently search seven policy documents by hand.<br>
                Developer: <strong>{metadata["developer"]}</strong> ({metadata["role"]})
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def _render_answer(result: Any) -> None:
    """Show the answer, its confidence, and the passages that produced it."""
    if not result.grounded:
        st.warning(result.answer)
        st.caption(
            f"Retrieval confidence {result.confidence:.3f} fell below the similarity floor, "
            "so the assistant refused instead of answering from a weak match."
        )
    else:
        st.markdown("#### Answer")
        st.markdown(result.answer)
        st.caption(
            "Every bracketed number points to a retrieved passage below. Nothing in this "
            "answer is generated text; each line is quoted from the policy library."
            if result.generator == "extractive"
            else f"Generated by `{result.generator}` under the grounding rules in prompts.py."
        )

    left, middle, right = st.columns(3)
    left.metric("Retrieval confidence", f"{result.confidence:.3f}")
    middle.metric("Passages used", len(result.passages))
    right.metric("Latency", f"{result.latency_ms:.0f} ms")

    if result.resolved_question != result.question:
        st.info(f"Follow-up resolved to: **{result.resolved_question}**")

    if result.passages:
        st.markdown("#### Retrieved passages")
        for passage in result.passages:
            with st.expander(
                f"[{passage.rank}] {passage.chunk.citation} · score {passage.score:.3f}",
                expanded=(passage.rank == 1 and result.grounded),
            ):
                st.markdown(passage.chunk.text)
                st.caption(f"Source file: `{passage.chunk.document}` · chunk `{passage.chunk.chunk_id}`")

    for note in result.notes:
        st.caption(f"ℹ️ {note}")


def _render_ask_tab(assistant: AirlineKnowledgeAssistant) -> None:
    st.markdown("Ask a passenger-style question. The assistant answers only from the loaded policy documents.")

    with st.expander("Try one of these", expanded=False):
        columns = st.columns(2)
        for index, question in enumerate(SAMPLE_QUESTIONS):
            if columns[index % 2].button(question, key=f"ka_sample_{index}", width="stretch"):
                st.session_state.ka_question = question

    question = st.text_input(
        "Passenger question",
        key="ka_question",
        placeholder="e.g. How much do you charge for an extra kilo of baggage?",
    )

    with st.expander("Retrieval settings", expanded=False):
        col_a, col_b = st.columns(2)
        top_k = col_a.slider("Passages retrieved (top-k)", 1, 8, DEFAULT_TOP_K, key="ka_top_k")
        floor = col_b.slider(
            "Similarity floor",
            0.0,
            0.40,
            DEFAULT_SIMILARITY_FLOOR,
            0.01,
            key="ka_floor",
            help="Below this score the assistant refuses instead of answering. Lowering it "
            "towards zero disables the main hallucination control.",
        )
        use_history = st.checkbox(
            "Resolve follow-up questions using the previous turn",
            value=True,
            key="ka_use_history",
        )

    if not question.strip():
        st.caption("Enter a question above, or pick one of the samples, to see a grounded answer.")
        return

    history = st.session_state.get("ka_history", []) if use_history else []
    result = assistant.answer(question, history=history, top_k=top_k, similarity_floor=floor)

    _render_answer(result)

    turns = st.session_state.setdefault("ka_history", [])
    if not turns or turns[-1][0] != question:
        turns.append((question, result.answer))
        del turns[:-5]  # only the recent turns are useful for follow-up resolution

    st.download_button(
        "Download this answer as JSON",
        data=export_answer_json(result),
        file_name="indus_air_answer.json",
        mime="application/json",
        key="ka_download_answer",
    )

    if st.button("Clear conversation history", key="ka_clear"):
        st.session_state.ka_history = []
        st.rerun()


def _render_knowledge_base_tab(assistant: AirlineKnowledgeAssistant) -> None:
    stats = assistant.stats
    col_a, col_b, col_c, col_d = st.columns(4)
    col_a.metric("Documents", stats["documents"])
    col_b.metric("Chunks indexed", stats["chunks"])
    col_c.metric("Words", f"{stats['words']:,}")
    col_d.metric("Retrieval backend", stats["backend"])

    st.caption(
        f"Answer generation provider: `{stats['provider']}`. The default `mock` provider runs "
        "the pipeline entirely offline with no API key, which is what the deployed demo uses. "
        "Setting `LLM_PROVIDER=openai` with a key routes generation through the templates in "
        "`prompts.py` and keeps the extractive answer as the fallback."
    )

    st.markdown("#### Indexed documents")
    st.dataframe(
        pd.DataFrame(assistant.knowledge_base_summary()).rename(
            columns={
                "document": "File",
                "title": "Document title",
                "sections": "Sections",
                "chunks": "Chunks",
                "words": "Words",
            }
        ),
        width="stretch",
        hide_index=True,
    )

    st.markdown("#### Browse a document")
    documents = sorted({chunk.document for chunk in assistant.chunks})
    selected = st.selectbox("Policy document", documents, key="ka_doc_select")
    for chunk in [c for c in assistant.chunks if c.document == selected]:
        with st.expander(chunk.section if chunk.total_parts == 1 else f"{chunk.section} (part {chunk.part})"):
            st.markdown(chunk.text)


def _render_benchmark_tab(assistant: AirlineKnowledgeAssistant) -> None:
    st.markdown(
        "The gold set in `data/evaluation_set.json` was written from the agent's point of view "
        "using passenger phrasing, before the retriever was tuned. It measures the three ways "
        "this assistant can fail an agent: retrieving the wrong policy, answering a question it "
        "should have refused, or refusing one it should have answered."
    )

    if st.button("Run benchmark", type="primary", key="ka_run_benchmark"):
        with st.spinner("Scoring the pipeline against the gold set..."):
            st.session_state.ka_benchmark = assistant.evaluate()

    report = st.session_state.get("ka_benchmark")
    if not report:
        st.caption("Run the benchmark to see accuracy, refusal behaviour and per-question results.")
        return

    col_a, col_b, col_c, col_d = st.columns(4)
    col_a.metric("Answer accuracy", f"{report['answer_accuracy']}%")
    col_b.metric("Refusal accuracy", f"{report['refusal_accuracy']}%")
    col_c.metric("Recall@k", f"{report['retrieval_recall_at_k']}%")
    col_d.metric("Precision@1", f"{report['retrieval_precision_at_1']}%")

    st.caption(
        f"{report['answerable_cases']} answerable questions and {report['out_of_scope_cases']} "
        f"out-of-scope questions, mean latency {report['mean_latency_ms']} ms per question."
    )

    frame = pd.DataFrame(report["rows"])
    show_failures = st.checkbox("Show only incorrect cases", value=False, key="ka_only_failures")
    if show_failures:
        frame = frame[~frame["correct"]]
        if frame.empty:
            st.success("Every case in the gold set passed.")
            return

    st.dataframe(
        frame[
            [
                "question",
                "expected_document",
                "retrieved_document",
                "hit_at_1",
                "grounded",
                "should_refuse",
                "correct",
                "confidence",
            ]
        ].rename(
            columns={
                "question": "Question",
                "expected_document": "Expected document",
                "retrieved_document": "Top-1 retrieved",
                "hit_at_1": "Top-1 correct",
                "grounded": "Answered",
                "should_refuse": "Should refuse",
                "correct": "Correct",
                "confidence": "Confidence",
            }
        ),
        width="stretch",
        hide_index=True,
    )


def _render_how_it_works_tab(assistant: AirlineKnowledgeAssistant) -> None:
    st.markdown(
        """
#### Pipeline

1. **Chunking** - each policy document is split at its own level-two headings, so a
   retrieved passage is a complete rule an agent can read and act on. Sections longer
   than 1,100 characters are split at paragraph boundaries with a small overlap.
2. **Query expansion** - passengers say "hand luggage", the policy says "cabin baggage".
   A domain synonym map bridges that gap before vectorisation, which is what lets lexical
   retrieval work without an embeddings service.
3. **Vector index** - TF-IDF over unigrams and bigrams, scored by cosine similarity,
   behind a `VectorIndex` interface. `EmbeddingVectorIndex` implements the same interface
   against a hosted embeddings API and swaps in without touching anything downstream.
4. **Similarity floor** - if the best passage scores below the floor, the assistant
   refuses instead of answering from a weak match.
5. **Grounded composition** - the answer quotes the passage lines that match the question
   and tags each with its passage number.

#### Hallucination controls

- A **similarity floor** that turns weak retrieval into an explicit refusal that names the
  closest covered topic, instead of a confident-sounding guess.
- **Extractive composition** in offline mode: every line of the answer is verbatim text
  from a retrieved passage, so there is no text for the system to invent.
- **Prompt rules** in `prompts.py` for provider mode, which forbid outside knowledge,
  require a citation per claim, and require figures to be quoted exactly.
- **Visible citations and scores** on every answer, so an agent can check the source
  before repeating it to a passenger.
        """
    )

    st.markdown("#### Prompt sent in provider mode")
    st.caption(
        "This is the exact prompt the assistant would send to a hosted model. It is rendered "
        "even in offline mode so the grounding rules can be reviewed."
    )
    with st.expander("System prompt"):
        from src.modules.knowledge_assistant_airline import prompts as prompt_module

        st.code(prompt_module.SYSTEM_PROMPT, language="text")

    preview_question = st.text_input(
        "Preview the user-side prompt for a question",
        value="How much do you charge per kilo for overweight bags on a domestic flight?",
        key="ka_prompt_preview_q",
    )
    if preview_question.strip():
        result = assistant.answer(preview_question)
        if result.prompt_preview:
            st.code(result.prompt_preview, language="text")
        else:
            st.caption("This question was refused, so no prompt would be sent to a provider.")


def render_ui() -> None:
    """Entry point called by the shared Week 4 Streamlit shell."""
    metadata = MODULE_REGISTRY["week4"]["knowledge_assistant_airline"]
    _render_header(metadata)

    try:
        assistant = _load_assistant()
    except Exception as exc:
        st.error("The knowledge base could not be loaded.")
        st.exception(exc)
        return

    ask_tab, kb_tab, benchmark_tab, how_tab = st.tabs(
        ["Ask the assistant", "Knowledge base", "Benchmark", "How it works"]
    )

    with ask_tab:
        _render_ask_tab(assistant)
    with kb_tab:
        _render_knowledge_base_tab(assistant)
    with benchmark_tab:
        _render_benchmark_tab(assistant)
    with how_tab:
        _render_how_it_works_tab(assistant)
