"""Build a standalone deployment package for the Indus Air RAG Knowledge Assistant.

Week 4 Client-Ready Sprint module owned by Muhammad Faozan Mujtaba.

The shared ``week4/deploy_prep.py`` packages the group leader's chatbot module and
hardcodes its paths, and it is a shared file that other members' pull requests also touch.
This module-local script does the same job for this module, following the precedent set by
``week4/tutor_deploy_package/``.

Run it from the ``week4`` folder:

    python src/modules/knowledge_assistant_airline/deploy_prep.py

It writes ``week4/knowledge_assistant_deploy_package/``, which is a self-contained
Streamlit app: its own ``app.py``, its own ``requirements.txt``, a trimmed ``registry.py``
and a copy of the knowledge base.

The package keeps the module's real import paths (``src.modules.knowledge_assistant_airline``)
rather than flattening them, so the deployed code is byte-identical to the reviewed code
and no import rewriting can silently change behaviour between the two.
"""

from __future__ import annotations

import shutil
from pathlib import Path

MODULE_DIR = Path(__file__).resolve().parent
WEEK4_DIR = MODULE_DIR.parents[2]
PACKAGE_DIR = WEEK4_DIR / "airline_deploy_package"
MODULE_NAME = "knowledge_assistant_airline"

APP_ENTRYPOINT = '''"""Standalone entrypoint for the Indus Air RAG Knowledge Assistant.

Generated by src/modules/knowledge_assistant_airline/deploy_prep.py - do not edit here.
Edit the module in week4/src/modules/knowledge_assistant_airline/ and regenerate.
"""

import sys
from pathlib import Path

import streamlit as st

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

st.set_page_config(
    page_title="Indus Air Knowledge Assistant",
    page_icon="📚",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# Standalone deployment has no shared shell, so the module supplies its own styling.
st.markdown(
    """
    <style>
    [data-testid="stSidebarNav"] { display: none !important; }
    footer { visibility: hidden; }
    .block-container { max-width: 1180px; padding-top: 3rem; padding-bottom: 4rem; }
    .hero-wrap { background: rgba(127, 127, 127, 0.06); border: 1px solid rgba(127, 127, 127, 0.25);
        border-radius: 12px; padding: 1.5rem 1.75rem; margin-bottom: 1.5rem; }
    .hero-badge { display: inline-block; font-size: 0.75rem; font-weight: 700; text-transform: uppercase;
        letter-spacing: 0.05em; color: #0f766e; background: #e6f5f2; padding: 0.25rem 0.6rem;
        border-radius: 999px; margin-bottom: 0.5rem; }
    .hero-title { font-size: 1.6rem; font-weight: 800; margin-bottom: 0.25rem; }
    .hero-subtitle { font-size: 0.95rem; opacity: 0.8; line-height: 1.5; }
    </style>
    """,
    unsafe_allow_html=True,
)

from src.modules.knowledge_assistant_airline.ui import render_ui

if __name__ == "__main__":
    render_ui()
'''

# Only what this module actually imports. No scikit-learn extras, no openpyxl, no
# matplotlib: a smaller install is a faster and more reliable cold start on free hosting.
REQUIREMENTS = """streamlit>=1.36.0
pandas>=2.0.0
numpy>=1.24.0
scikit-learn>=1.2.0
"""

# ui.py reads its title and developer metadata from the registry, so the package needs a
# registry containing this module's entry. Team emails are deliberately left out of the
# public deployment.
REGISTRY = '''"""Trimmed registry for the standalone deployment of this module."""

MODULE_REGISTRY = {
    "week4": {
        "knowledge_assistant_airline": {
            "title": "RAG-based Knowledge Assistant",
            "developer": "Muhammad Faozan Mujtaba",
            "role": "Group Member",
            "status": "Submission Ready",
            "tech": ["Python", "scikit-learn", "TF-IDF Retrieval", "RAG Pipeline", "Streamlit"],
            "description": (
                "Retrieval-Augmented Generation assistant answering Q&A queries over a "
                "customised operational document set (FAQ/policies) with citations and "
                "an explicit refusal path for out-of-scope questions."
            ),
            "import_path": "src.modules.knowledge_assistant_airline.ui",
            "icon": "\\U0001F4DA",
            "deployed_url": None,
        }
    }
}
'''

PACKAGE_INIT = '"""Standalone deployment package for the Indus Air Knowledge Assistant."""\n'

# Copied verbatim from the module. Tests and internal docs are left behind: they are not
# needed to serve the app and only slow the deployment build.
SOURCE_FILES = ["__init__.py", "engine.py", "prompts.py", "ui.py"]


def prepare_standalone_package() -> Path:
    """Create the deployment folder and return its path."""
    print("=" * 70)
    print("  SafeX Group 54 - Indus Air Knowledge Assistant Packager")
    print("=" * 70)

    if PACKAGE_DIR.exists():
        shutil.rmtree(PACKAGE_DIR)

    module_target = PACKAGE_DIR / "src" / "modules" / MODULE_NAME
    module_target.mkdir(parents=True, exist_ok=True)
    print(f"[+] Created package directory: {PACKAGE_DIR}")

    missing = [name for name in SOURCE_FILES if not (MODULE_DIR / name).exists()]
    if missing:
        raise FileNotFoundError(f"Module source files missing: {', '.join(missing)}")

    for name in SOURCE_FILES:
        shutil.copy2(MODULE_DIR / name, module_target / name)
    print(f"[+] Copied {len(SOURCE_FILES)} module source files (imports unchanged).")

    shutil.copytree(MODULE_DIR / "data", module_target / "data")
    document_count = len(list((module_target / "data" / "knowledge_base").glob("*.md")))
    print(f"[+] Copied knowledge base ({document_count} policy documents) and evaluation set.")

    (PACKAGE_DIR / "src" / "__init__.py").write_text(PACKAGE_INIT, encoding="utf-8")
    (PACKAGE_DIR / "src" / "modules" / "__init__.py").write_text(PACKAGE_INIT, encoding="utf-8")
    (PACKAGE_DIR / "src" / "modules" / "registry.py").write_text(REGISTRY, encoding="utf-8")
    print("[+] Wrote package __init__ files and trimmed registry.")

    (PACKAGE_DIR / "app.py").write_text(APP_ENTRYPOINT, encoding="utf-8")
    (PACKAGE_DIR / "requirements.txt").write_text(REQUIREMENTS, encoding="utf-8")
    print("[+] Wrote standalone app.py and requirements.txt.")

    print("\n" + "=" * 70)
    print("  PACKAGE READY")
    print("=" * 70)
    print(f"Location: {PACKAGE_DIR}\n")
    print("Verify locally before deploying:")
    print(f"   cd {PACKAGE_DIR}")
    print("   streamlit run app.py\n")
    print("Deploy on Streamlit Community Cloud:")
    print("   git init && git add . && git commit -m 'Indus Air knowledge assistant'")
    print("   git remote add origin <your-personal-github-repo-url>")
    print("   git push -u origin main")
    print("   Then open share.streamlit.io, pick the repo, and set the main file to app.py.")
    print("   No secrets are required: the app runs offline with no API key.\n")
    print("Finally, set 'deployed_url' for knowledge_assistant_airline in")
    print("week4/src/modules/registry.py to the live link.")
    print("=" * 70)
    return PACKAGE_DIR


if __name__ == "__main__":
    prepare_standalone_package()
